name: Acquire activation file
on:
Â  workflow_dispatch: {}
jobs:
Â  activation:
Â  Â  name: Request manual activation file ðŸ”‘
Â  Â  runs-on: ubuntu-latest
Â  Â  steps:
Â  Â  Â  # Request manual activation file
Â  Â  Â  - name: Request manual activation file
Â  Â  Â  Â  id: getManualLicenseFile
Â  Â  Â  Â  uses: game-ci/unity-request-activation-file@v2
Â  Â  Â  # Upload artifact (Unity_v20XX.X.XXXX.alf)
Â  Â  Â  - name: Expose as artifact
Â  Â  Â  Â  uses: actions/upload-artifact@v2
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  name: ${{ steps.getManualLicenseFile.outputs.filePath }}
Â  Â  Â  Â  Â  path: ${{ steps.getManualLicenseFile.outputs.filePath }}
